import {
    IconAnchor,
    IconBrandGolang,
    IconBrandJavascript,
    IconBrandMongodb,
    IconBrandMysql,
    IconBrandNextjs,
    IconBrandNodejs,
    IconBrandPhp,
    IconBrandReact,
    IconBrandSymfony,
    IconBrandTypescript,
    IconCode,
    IconCurrencyBitcoin,
    IconCurrencyEthereum,
    IconCurrencySolana,
    IconDatabase,
    IconServer,
    IconWorldWww
} from '@tabler/icons-react';

export const IconMap = {
    IconCurrencyBitcoin,
    IconCurrencyEthereum,
    IconCurrencySolana,
    IconAnchor,
    IconWorldWww,
    IconBrandNodejs,
    IconBrandGolang,
    IconBrandPhp,
    IconBrandSymfony,
    IconCode,
    IconBrandReact,
    IconBrandNextjs,
    IconBrandJavascript,
    IconBrandTypescript,
    IconDatabase,
    IconBrandMongodb,
    IconBrandMysql,
    IconServer
} as const;
